'use client'
import * as React from 'react'
import { CalendarCheck2, Clock3, Phone, Scissors } from 'lucide-react'
import { toast } from 'sonner'
import { MonthCalendar } from './month-calendar'
import { Button } from '@/components/ui/button'
import { bookSlot, getAvailableDays, getMyBookings, getOpenSlots, cancelMyBooking } from '@/app/actions/appointments'
import { formatLongDate, formatMoney, toDateKey } from '@/lib/slots'

type Slot={id:number;slotDate:string;slotTime:string;status:string;price:number}
export function ClientBooking(){
 const [date,setDate]=React.useState(toDateKey(new Date()));const [slots,setSlots]=React.useState<Slot[]>([]);const [days,setDays]=React.useState<Array<{dateKey:string;openCount:number}>>([]);const [mine,setMine]=React.useState<Slot[]>([]);const [phone,setPhone]=React.useState('');const [busy,setBusy]=React.useState(false)
 const refresh=React.useCallback(async()=>{const [a,b,c]=await Promise.all([getOpenSlots(date),getAvailableDays(),getMyBookings()]);setSlots(a as Slot[]);setDays(b);setMine(c as Slot[])},[date]);React.useEffect(()=>{refresh()},[refresh]);const markers = Object.fromEntries(days.map(d => [d.dateKey, 'available' as const]))
 async function book(id:number){if(phone.trim().length<8){toast.error('Informe seu WhatsApp antes de reservar.');return}setBusy(true);try{const r=await bookSlot(id,phone);r.ok?toast.success('Horário reservado!'):toast.error(r.message);await refresh()}finally{setBusy(false)}}
 return <div className="min-h-svh bg-[radial-gradient(circle_at_top_right,rgba(192,145,72,.13),transparent_28%),linear-gradient(180deg,#151516,#0f0f10)]"><header className="border-b border-white/10"><div className="mx-auto max-w-7xl px-5 py-5"><p className="text-xs uppercase tracking-[.24em] text-primary">Nunex Cortes</p><h1 className="font-sans text-2xl font-bold uppercase">Agende com o Nuno</h1></div></header><main className="mx-auto grid max-w-7xl gap-5 px-5 py-6 lg:grid-cols-[340px_1fr]"><aside className="space-y-4"><MonthCalendar selected={date} onSelect={setDate} markers={markers}/><div className="rounded-3xl border border-white/10 bg-card/60 p-5"><label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground"><Phone className="size-4 text-primary"/>WhatsApp</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(27) 99999-9999" className="mt-3 w-full rounded-xl border border-border bg-background px-3 py-3 outline-none focus:ring-2 focus:ring-primary/50"/><p className="mt-2 text-xs text-muted-foreground">Usaremos apenas para identificar e confirmar seu horário.</p></div></aside><section className="space-y-5"><div className="rounded-3xl border border-white/10 bg-card/50 p-5"><div className="flex items-center gap-2 text-primary"><CalendarCheck2 className="size-4"/><span className="text-xs font-semibold uppercase tracking-widest">Escolha o horário</span></div><h2 className="mt-1 font-sans text-2xl font-bold uppercase">{formatLongDate(date)}</h2><p className="mt-1 text-sm text-muted-foreground">Cada atendimento ocupa 45 minutos. Só aparecem horários realmente livres.</p></div>{slots.length?<div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4">{slots.map(s=><button disabled={busy} onClick={()=>book(s.id)} key={s.id} className="group rounded-2xl border border-white/10 bg-card/60 p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/45 hover:bg-primary/[.07]"><Clock3 className="mb-3 size-4 text-primary"/><p className="font-sans text-xl font-bold">{s.slotTime}</p><p className="mt-1 text-xs text-muted-foreground">{formatMoney(s.price||0)}</p><span className="mt-3 inline-block text-xs font-semibold text-primary opacity-70 group-hover:opacity-100">Reservar →</span></button>)}</div>:<div className="rounded-3xl border border-dashed border-white/15 p-10 text-center"><Scissors className="mx-auto mb-3 size-7 text-primary"/><p className="font-semibold">Nenhum horário livre neste dia.</p><p className="mt-1 text-sm text-muted-foreground">Escolha outro dia no calendário.</p></div>}
 {mine.length>0&&<div className="rounded-3xl border border-white/10 bg-card/40 p-5"><h3 className="font-sans text-lg font-bold uppercase">Meus agendamentos</h3><div className="mt-3 space-y-2">{mine.map(s=><div key={s.id} className="flex items-center justify-between gap-3 rounded-xl bg-white/[.03] p-3"><div><p className="font-semibold">{s.slotDate} • {s.slotTime}</p></div><Button variant="ghost" size="sm" onClick={async()=>{await cancelMyBooking(s.id);toast.success('Agendamento cancelado');await refresh()}}>Cancelar</Button></div>)}</div></div>}
 </section></main></div>}
